### ISSUE TITLE
My profile page: add picture and name 

### ISSUE THREAD

**Issue by uly-ana** [rayhanw/rentscootscoot#79]
My profile should have an avatar picture and name. Right now we have a default picture and name.

**Comment by uly-ana** [comment]
it also has About me info. But there is no form that asks user to add it or edit.

**Comment by rayhanw** [comment]
Picture defaults to that white basic Facebook avatar if you didn't upload an avatar during registration.
Same goes for name, but it defaults to John Doe if you didn't input a name in (also during registration)

We should implement an edit for profile though, I agree
